### ISSUE TITLE
面板启动失败，可能是因为启动时间超过了两秒，请稍后查看日志信息

### ISSUE THREAD

**Issue by xc1988** [sprov065/v2-ui#32]
● v2-ui.service – v2-ui Service
Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Fri 2019-08-16 10:12:51 CST; 21s ago
Process: 753 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=255)
Main PID: 753 (code=exited, status=255)

Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: File “apscheduler/schedulers/base.py”, line 126, in con
Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: File “apscheduler/schedulers/background.py”, line 29, i
Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: File “apscheduler/schedulers/base.py”, line 697, in _co
Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: File “tzlocal/unix.py”, line 165, in get_localzone
Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: File “tzlocal/unix.py”, line 90, in _get_localzone
Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: File “tzlocal/utils.py”, line 38, in assert_tz_offset
Aug 16 10:12:51 ONEVPS190816011025 v2-ui[753]: ValueError: Timezone offset does not match system offset:
Aug 16 10:12:51 ONEVPS190816011025 systemd[1]: v2-ui.service: Main process exited, code=exited, status=2
Aug 16 10:12:51 ONEVPS190816011025 systemd[1]: v2-ui.service: Unit entered failed state.
Aug 16 10:12:51 ONEVPS190816011025 systemd[1]: v2-ui.service: Failed with result ‘exit-code’.

**Comment by sprov065** [comment]
你们这些改时区的到底怎么操作的，我怎么一点也操作不出来

**Comment by sprov065** [comment]
尝试更新面板

**Comment by vayci** [comment]
请输入选择 [0-14]: 10
● v2-ui.service - v2-ui Service
   Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-08-20 13:11:28 CST; 1min 23s ago
  Process: 17526 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=255)
 Main PID: 17526 (code=exited, status=255)

Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "util/v2_jobs.py", line 4, in <module>
Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "/root/v-v2-ui/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "util/v2_util.py", line 100, in <module>
Aug 20 13:11:28 vultr.guest v2-ui[17526]: NameError: name 'exit' is not defined
Aug 20 13:11:28 vultr.guest systemd[1]: v2-ui.service: main process exited, code=exited, status=255/n/a
Aug 20 13:11:28 vultr.guest systemd[1]: Unit v2-ui.service entered failed state.
Aug 20 13:11:28 vultr.guest systemd[1]: v2-ui.service failed.

**Comment by sprov065** [comment]
> 请输入选择 [0-14]: 10
> ● v2-ui.service - v2-ui Service
> Loaded: loaded (/etc/systemd/system/v2-ui.service; enabled; vendor preset: disabled)
> Active: failed (Result: exit-code) since Tue 2019-08-20 13:11:28 CST; 1min 23s ago
> Process: 17526 ExecStart=/usr/local/v2-ui/v2-ui (code=exited, status=255)
> Main PID: 17526 (code=exited, status=255)
> 
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "util/v2_jobs.py", line 4, in 
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "", line 971, in _find_and_load
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "", line 955, in _find_and_load_unlocked
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "", line 665, in _load_unlocked
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "/root/v-v2-ui/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: File "util/v2_util.py", line 100, in 
> Aug 20 13:11:28 vultr.guest v2-ui[17526]: NameError: name 'exit' is not defined
> Aug 20 13:11:28 vultr.guest systemd[1]: v2-ui.service: main process exited, code=exited, status=255/n/a
> Aug 20 13:11:28 vultr.guest systemd[1]: Unit v2-ui.service entered failed state.
> Aug 20 13:11:28 vultr.guest systemd[1]: v2-ui.service failed.

你自己把 v2ray 配置模板搞乱了，重置面板设置吧，还有不要回复已经关闭的 issue，要么就自己新开一个 issue。
